name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Create terraform.tfvars
        run: |
          cat <<EOF > terraform.tfvars
          ${{ secrets.TERRAFORM_TFVARS }}
          EOF

      - name: Terraform Init
        run: terraform init
        env:
          ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}

      - name: Terraform Plan
        if: github.event.inputs.action == 'plan'
        run: terraform plan -out=tfplan -var-file=terraform.tfvars -lock=false
        env:
          ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve -var-file=terraform.tfvars -lock=false
        env:
          ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve -var-file=terraform.tfvars -lock=false
        env:
          ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}
